CREATE TABLE Vendas.FAT_Itens_Nota
(
    COD_TEMP INT NOT NULL,
    COD_PROD INT NOT NULL,
    COD_FORN INT NOT NULL,
    COD_CLI INT NOT NULL,
    COD_PARC INT NOT NULL,
    NUM_NOTA INT NOT NULL,
    NUM_PED INT NOT NULL,
    QTD_PED INT NOT NULL,
    PRECO_PRO FLOAT(2) NOT NULL
)
