CREATE TABLE Vendas.DIM_Clientes
(
    COD_CLI INT NOT NULL,
    LIM_CREDITO FLOAT(2) NOT NULL,
    SLD_DEVEDOR FLOAT(2) NOT NULL,
    NOM_CLI VARCHAR(40) NOT NULL,
    FONES VARCHAR(30) NOT NULL
)

ALTER TABLE Vendas.DIM_Clientes
   ADD CONSTRAINT PK_DIM_Clientes_COD_CLI PRIMARY KEY CLUSTERED (COD_CLI);

ALTER TABLE Vendas.FAT_Itens_Nota
ADD CONSTRAINT COD_CLI
FOREIGN KEY (COD_CLI) REFERENCES Vendas.DIM_Clientes(COD_CLI);
