CREATE TABLE Vendas.DIM_Fornecedores
(
    COD_FORN INT NOT NULL,
    UF_FORN CHAR(2) NOT NULL,
    SLD_CREDOR FLOAT(2) NOT NULL,
    NOM_FORN VARCHAR(40) NOT NULL
)

ALTER TABLE Vendas.DIM_Fornecedores
   ADD CONSTRAINT PK_DIM_Fornecedores_COD_FORN PRIMARY KEY CLUSTERED (COD_FORN);

ALTER TABLE Vendas.FAT_Itens_Nota
ADD CONSTRAINT COD_FORN
FOREIGN KEY (COD_FORN) REFERENCES Vendas.DIM_Fornecedores(COD_FORN);
