CREATE TABLE Vendas.DIM_Produtos
(
    COD_PROD INT NOT NULL,
    QTD_ESTOQUE INT NOT NULL,
    PER_PARC CHAR(1) NOT NULL,
    PRECO_PRO FLOAT(2) NOT NULL,
    DSC_PRO VARCHAR(40) NOT NULL
)

ALTER TABLE Vendas.DIM_Produtos
   ADD CONSTRAINT PK_DIM_Produtos_COD_PROD PRIMARY KEY CLUSTERED (COD_PROD);

ALTER TABLE Vendas.FAT_Itens_Nota
ADD CONSTRAINT COD_PROD
FOREIGN KEY (COD_PROD) REFERENCES Vendas.DIM_Produtos(COD_PROD);
