CREATE TABLE Vendas.DIM_Pedidos
(
    NUM_PED INT NOT NULL,
    DAT_PED DATETIME NOT NULL,
    STA_PEDIDO CHAR(1) NOT NULL,
    VAL_PED FLOAT(2) NOT NULL,
    VAL_A_VISTA FLOAT(2) NOT NULL,
    VAL_A_PRAZO FLOAT(2) NOT NULL,
    SLD_DEVEDOR FLOAT(2) NOT NULL
)

ALTER TABLE Vendas.DIM_Pedidos
   ADD CONSTRAINT PK_DIM_Pedidos_NUM_PED PRIMARY KEY CLUSTERED (NUM_PED);

ALTER TABLE Vendas.FAT_Itens_Nota
ADD CONSTRAINT NUM_PED
FOREIGN KEY (NUM_PED) REFERENCES Vendas.DIM_Pedidos(NUM_PED);
