CREATE TABLE Vendas.DIM_Temporal
(
    COD_TEMP INT NOT NULL,
    DAT_DIA INT NOT NULL,
    DAT_MES INT NOT NULL,
    DAT_ANO INT NOT NULL
)

ALTER TABLE Vendas.DIM_Temporal
   ADD CONSTRAINT PK_DIM_Temporal_COD_TEMP PRIMARY KEY CLUSTERED (COD_TEMP);

ALTER TABLE Vendas.FAT_Itens_Nota
ADD CONSTRAINT COD_TEMP
FOREIGN KEY (COD_TEMP) REFERENCES Vendas.DIM_Temporal(COD_TEMP);
