CREATE SCHEMA BolsaFamilia;

CREATE TABLE BolsaFamilia.Dados
(
    ID INT NOT NULL,
    DATA_REFERENCIA DATETIME NOT NULL,
    VALOR DECIMAL NOT NULL,
    QTD_BENEFICIADOS INT NOT NULL,
    NOME_IBGE VARCHAR(50) NOT NULL,
    SIGLA CHAR(2) NOT NULL,
    NOME VARCHAR(50) NOT NULL
)

Select *
from BolsaFamilia.Dados;
