CREATE SCHEMA BolsaFamiliaDW;

-- FT_Registros
CREATE TABLE BolsaFamiliaDW.FT_Registros
(
    ID_CIDADE INT NOT NULL,
    ID_TEMPO INT NOT NULL,
    VLR_GASTO DECIMAL NOT NULL,
    QTD_BENEFICIADOS INT NOT NULL
);

ALTER TABLE BolsaFamiliaDW.FT_Registros
   ADD CONSTRAINT PK_FT_Registros PRIMARY KEY CLUSTERED (ID_CIDADE, ID_TEMPO);

-- DM_Cidade
CREATE TABLE BolsaFamiliaDW.DM_Cidade
(
    ID_CIDADE INT IDENTITY NOT NULL,
    NOM_CIDADE VARCHAR(50) NOT NULL,
    NOM_UF VARCHAR(50) NOT NULL,
    SGL_UF CHAR(2) NOT NULL
)

ALTER TABLE BolsaFamiliaDW.DM_Cidade
   ADD CONSTRAINT PK_DM_Cidade_ID_CIDADE PRIMARY KEY CLUSTERED (ID_CIDADE);

ALTER TABLE BolsaFamiliaDW.FT_Registros
ADD CONSTRAINT ID_CIDADE
FOREIGN KEY (ID_CIDADE) REFERENCES BolsaFamiliaDW.DM_Cidade(ID_CIDADE);

-- DM_Tempo
CREATE TABLE BolsaFamiliaDW.DM_Tempo
(
    ID_TEMPO INT IDENTITY NOT NULL,
    NUM_MES INT NOT NULL,
    NUM_ANO INT NOT NULL
)

ALTER TABLE BolsaFamiliaDW.DM_Tempo
   ADD CONSTRAINT PK_DM_Tempo_ID_TEMPO PRIMARY KEY CLUSTERED (ID_TEMPO);

ALTER TABLE BolsaFamiliaDW.FT_Registros
ADD CONSTRAINT ID_TEMPO
FOREIGN KEY (ID_TEMPO) REFERENCES BolsaFamiliaDW.DM_Tempo(ID_TEMPO);
