CREATE TABLE LocadoraDW.FT_Locacoes
(
    ID_SOC INT NOT NULL,
    ID_TITULO INT NOT NULL,
    ID_ART INT NOT NULL,
    ID_GRAV INT NOT NULL,
    ID_TEMPO INT NOT NULL,
    VALOR_ARRECADADO DECIMAL(2) NOT NULL,
    TEMPO_DEVOLUCAO DECIMAL(2) NOT NULL,
    MULTA_ATRASO DECIMAL(2) NOT NULL
)

ALTER TABLE LocadoraDW.FT_Locacoes
   ADD CONSTRAINT PK_FT_Locacoes_PK PRIMARY KEY CLUSTERED (ID_SOC, ID_TITULO, ID_ART, ID_GRAV, ID_TEMPO);
