CREATE TABLE LocadoraDW.DM_Artista
(
    ID_ART INT IDENTITY NOT NULL,
    TPO_ART VARCHAR(40) NOT NULL,
    NAC_BRAS VARCHAR(40) NOT NULL,
    NOM_ART VARCHAR(40) NOT NULL
)

ALTER TABLE LocadoraDW.DM_Artista
   ADD CONSTRAINT PK_DM_Artista_ID_ART PRIMARY KEY CLUSTERED (ID_ART);

ALTER TABLE LocadoraDW.FT_Locacoes
ADD CONSTRAINT ID_ART
FOREIGN KEY (ID_ART) REFERENCES LocadoraDW.DM_Artista(ID_ART);
