CREATE TABLE LocadoraDW.DM_Gravadora
(
    ID_GRAV INT IDENTITY NOT NULL,
    UF_GRAV VARCHAR(50) NOT NULL,
    NAC_BRAS VARCHAR(30) NOT NULL,
    NOM_GRAV VARCHAR(40) NOT NULL,
)

ALTER TABLE LocadoraDW.DM_Gravadora
   ADD CONSTRAINT PK_DM_Gravadora_ID_GRAV PRIMARY KEY CLUSTERED (ID_GRAV);

ALTER TABLE LocadoraDW.FT_Locacoes
ADD CONSTRAINT ID_GRAV
FOREIGN KEY (ID_GRAV) REFERENCES LocadoraDW.DM_Gravadora(ID_GRAV);
