CREATE TABLE LocadoraDW.DM_Tempo
(
    ID_TEMPO INT IDENTITY NOT NULL,
    NU_ANO INT NOT NULL,
    NU_MES INT NOT NULL,
    NU_ANOMES INT NOT NULL,
    SG_MES CHAR(3) NOT NULL,
    NM_MESANO CHAR(8) NOT NULL,
    NM_MES VARCHAR(15) NOT NULL,
    NU_DIA INT NOT NULL,
    DT_TEMPO DATETIMEOFFSET NOT NULL,
    NU_HORA INT NOT NULL,
    TURNO VARCHAR(30) NOT NULL
)

ALTER TABLE LocadoraDW.DM_Tempo
   ADD CONSTRAINT PK_DM_Tempo_ID_TEMPO PRIMARY KEY CLUSTERED (ID_TEMPO);

ALTER TABLE LocadoraDW.FT_Locacoes
ADD CONSTRAINT ID_TEMPO
FOREIGN KEY (ID_TEMPO) REFERENCES LocadoraDW.DM_Tempo(ID_TEMPO);
